encoding: utf-8

baseurl: "http://www.javascript-online-lernen.de"

syntax-highlighting:
  enabled : true
  css: syntax.css

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      author: "Dirk Einecke"
