encoding: utf-8
timezone: Europe/Berlin

baseurl: http://www.javascript-online-lernen.de

syntax-highlighting:
  enabled : true
  css: syntax.css

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      author: Dirk Einecke
